### ISSUE TITLE
FedUni texture IRIs at RVA have two different values

### ISSUE THREAD

**Issue by meganrwong** [FedUni-CeRDI/def-au-edu-feduni#12]
The FedUni texture IRIs at RVA have two different values, one with “soil”, “edu” and “result” in it.
http://anzsoil.org/def/soil/au/edu/fed-uni/result/texture-grade/C or http://anzsoil.org/def/au/fed-uni/texture-grade/C 
The first is at http://vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-implemented-through-federation-u/fedusoil-1-0-0/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Ftexture-grade%2FC 
The second at Soil Vocabularies implemented through Federation University - Research Vocabularies Australia (ardc.edu.au))

**Comment by meganrwong** [comment]
Will work to update IRI to not include /result/  
Thank you for alerting to @bsimons14
at https://vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-implemented-through-federation-u/fedusoil-1-0-0/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Ftexture-grade%2FC

**Comment by meganrwong** [comment]
can you check this version in RVA demo mode is ok  to resolve this issue @bsimons14 ?
https://demo.vocabs.ardc.edu.au/viewById/900

**Comment by meganrwong** [comment]
@bsimons14 I just spotted another two mistakes soil/ and lismore/ ....... will fix

**Comment by meganrwong** [comment]
ok think this is right now could you look at @bsimons14 
https://demo.vocabs.ardc.edu.au/viewById/900

**Comment by bsimons14** [comment]
![image](https://user-images.githubusercontent.com/8413929/170174695-18e3eb68-1916-4a89-89bc-d4b986c05e21.png)

Top line has: http://anzsoil.org/def/au/fed-uni/texture-grade/C
Identifier has: http://anzsoil.org/def/soil/au/edu/fed-uni/result/texture-grade/C

Maybe not updated at ARDC yet?

**Comment by meganrwong** [comment]
https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Ftexture-grade

**Comment by meganrwong** [comment]
colours
https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fcolour

**Comment by bsimons14** [comment]
Colours good

**Comment by bsimons14** [comment]
Texture grade still has "edu" in it

**Comment by meganrwong** [comment]
thanks....... I notice edu in a few places

**Comment by meganrwong** [comment]
getting rid of edu was something that Simon and I decided to get out. Now I recall that.

**Comment by meganrwong** [comment]
try these now - 
https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fcolour

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Flismore

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fobject

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fprocedure

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fproperty

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Ftexture-grade

https://demo.vocabs.ardc.edu.au/repository/api/lda/ub/soil-vocabularies-coordinated-through-federation-u/test6/resource?uri=http%3A%2F%2Fanzsoil.org%2Fdef%2Fau%2Ffed-uni%2Fstructure-pedality-type

**Comment by bsimons14** [comment]
OK
